spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchange
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
       hibernate:
         format_sql: true
    show-sql: true